### ISSUE TITLE
SyntaxError: Non-ASCII character '\xe2' in file Injectus.py

### ISSUE THREAD

**Issue by catekuser** [BountyStrike/Injectus#2]
Hi,
When run:
root@kali:~/Injectus# python Injectus.py -h 
Receive the following error:
File "Injectus.py", line 33
SyntaxError: Non-ASCII character '\xe2' in file Injectus.py on line 34, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Any help on this, thanks.

**Comment by tanujjane** [comment]
python3 Injectus.py -h

**Comment by dubs3c** [comment]
You need to use at least python 3.7.

**Comment by JeffreyShran** [comment]
You most likely need to `apt install python3-dev`
